#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 母版页.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MedalSystem")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MedalSystemConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Medal_BonusPointMain> Medal_BonusPointMain
		{
			get
			{
				return this.GetTable<Medal_BonusPointMain>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Medal_BonusPointMain")]
	public partial class Medal_BonusPointMain
	{
		
		private int _Id;
		
		private string _UserId;
		
		private string _Name;
		
		private int _MedalId;
		
		private System.Nullable<double> _MedalValue;
		
		private System.Nullable<double> _IntegralValue;
		
		private System.Nullable<int> _MedalValueMax;
		
		private System.Nullable<int> _IntegralValueMax;
		
		private System.Nullable<int> _Level;
		
		public Medal_BonusPointMain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedalId", DbType="Int NOT NULL")]
		public int MedalId
		{
			get
			{
				return this._MedalId;
			}
			set
			{
				if ((this._MedalId != value))
				{
					this._MedalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedalValue", DbType="Float")]
		public System.Nullable<double> MedalValue
		{
			get
			{
				return this._MedalValue;
			}
			set
			{
				if ((this._MedalValue != value))
				{
					this._MedalValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntegralValue", DbType="Float")]
		public System.Nullable<double> IntegralValue
		{
			get
			{
				return this._IntegralValue;
			}
			set
			{
				if ((this._IntegralValue != value))
				{
					this._IntegralValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedalValueMax", DbType="Int")]
		public System.Nullable<int> MedalValueMax
		{
			get
			{
				return this._MedalValueMax;
			}
			set
			{
				if ((this._MedalValueMax != value))
				{
					this._MedalValueMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntegralValueMax", DbType="Int")]
		public System.Nullable<int> IntegralValueMax
		{
			get
			{
				return this._IntegralValueMax;
			}
			set
			{
				if ((this._IntegralValueMax != value))
				{
					this._IntegralValueMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
